authors:
 swapnilk:
    name: Swapnil Katarnavare
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/95159336
    url: https://github.com/Swappy200
  atharvab:
    name: Atharva Bhandvalkar
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/70326109
    url: https://github.com/a-tharva
  amanw:
    name: Aman Walekar
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/91743769
    url: https://github.com/AmanWalekar
  suraj:
    name: Suraj Jaiswal
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/143254595
    url: https://github.com/SurajJaiswal2002
  akashv:
    name: Akash Vyavhare
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/91061457
    url: https://github.com/akashvyavhare
  shreeyashs:
    name: Shreeyash Salunkhe
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/152859626?v=4
    url: https://github.com/Shreeyash09  
